export const DUX_KEYWORDS = [
  "DEFINE", "EVALUATE", "MEASURE", "RETURN", "VAR",
  "AND", "OR", "NOT", "TRUE", "FALSE",
];

export const DUX_BUILTINS = [
  "SUM", "AVERAGE", "COUNT", "COUNTA", "COUNTBLANK", "COUNTROWS", "DISTINCTCOUNT",
  "MIN", "MAX", "MEDIAN", "SUMX", "AVERAGEX", "COUNTX", "MINX", "MAXX", "CONCATENATEX",
  "SUMMARIZECOLUMNS", "FILTER", "CALCULATE", "ADDCOLUMNS", "SELECTCOLUMNS",
  "TOPN", "UNION", "INTERSECT", "EXCEPT", "VALUES", "DISTINCT", "TREATAS",
  "DIVIDE", "ISBLANK", "BLANK", "IF", "SWITCH",
];
