package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/danielwikar/dux/emitter"
)

func main() {
	names := emitter.ImplementedFunctions()
	quoted := make([]string, len(names))
	for i, name := range names {
		quoted[i] = fmt.Sprintf("%q", name)
	}
	content := "// Code generated by go generate ./...; DO NOT EDIT.\n\n" +
		"export const DUX_BUILTINS = [\n  " + strings.Join(quoted, ", ") + ",\n];\n"
	path := filepath.Join("..", "web", "core", "src", "duxFunctions.generated.ts")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		panic(err)
	}
}
